### ISSUE TITLE
Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper

### ISSUE THREAD

**Issue by Grawl** [algas/mastodon-local#1]
```
➜ docker-compose run --rm web rake assets:precompile
Starting mastodon-local_redis_1 ... done
Starting mastodon-local_db_1    ... done
yarn install v1.9.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.12s.
I, [2020-02-07T03:13:26.154129 #7]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2020-02-07T03:13:26.154660 #7]  INFO -- : Writing /mastodon/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2020-02-07T03:13:26.170108 #7]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2020-02-07T03:13:26.170320 #7]  INFO -- : Writing /mastodon/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2020-02-07T03:13:26.184227 #7]  INFO -- : Writing /mastodon/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2020-02-07T03:13:26.232595 #7]  INFO -- : Writing /mastodon/public/assets/pghero/application-b6568ba483c03c4fdcd8edd641f3b341ac0314ba01ab186645b8fc231cdff02e.js
I, [2020-02-07T03:13:26.252217 #7]  INFO -- : Writing /mastodon/public/assets/pghero/application-b6568ba483c03c4fdcd8edd641f3b341ac0314ba01ab186645b8fc231cdff02e.js.gz
I, [2020-02-07T03:13:26.393279 #7]  INFO -- : Writing /mastodon/public/assets/pghero/application-d7ee8e7dc0785de97337625e0f1030e1a892327ef4e72a48043ce09fd964874d.css
I, [2020-02-07T03:13:26.393617 #7]  INFO -- : Writing /mastodon/public/assets/pghero/application-d7ee8e7dc0785de97337625e0f1030e1a892327ef4e72a48043ce09fd964874d.css.gz
rake aborted!
Errno::EACCES: Permission denied @ dir_s_mkdir - /mastodon/public/assets/doorkeeper
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/asset.rb:163:in `write_to'
/mastodon/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:210:in `block (2 levels) in compile'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/mastodon/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

If I remove `volumes` section in `web` service,

```diff
services:
  ...
  web:
    ...
-    volumes:
-      - ./public/assets:/mastodon/public/assets
-      - ./public/system:/mastodon/public/system
```

it worked as expected:

```
➜ docker-compose run --rm web rake assets:precompile
Starting mastodon-local_redis_1 ... done
Starting mastodon-local_db_1    ... done
yarn install v1.9.4
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.04s.
Webpacker is installed 🎉 🍰
Using /mastodon/config/webpacker.yml file for setting up webpack paths
Compiling…
Compiled all packs in /mastodon/public/packs
  Rendering errors/500.html.haml within layouts/error
  Rendered errors/500.html.haml within layouts/error (959.0ms)
```

**Comment by technotariat** [comment]
Found https://github.com/tootsuite/mastodon/issues/6840 which suggests `chown -R 991:991 public`.
When I did this and re-ran `./setup.sh` this worked for me
